In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [2]:
b = np.array([[1, 2], [3, 4], [5, 6]])
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
print(c)

print(np.sum(a))
print(np.mean(a))

[5 7 9]
6
2.0


In [6]:
a = np.array([1, 2, 3])
print(a)
b = np.array([[1], [2], [3]])
print(b)

result = a + b
print(result)

[1 2 3]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [8]:
import numpy as np
import time

# Step 1: Define the size of the arrays
# We will create two large arrays with 1 million elements each

size = 1_000_000

# Step 2: Create two random arrays using NumPy
# These arrays will contain 'size' number of random floating point numbers between 0 and 1
array1 = np.random.rand(size)
array2 = np.random.rand(size)

#------------- Method 1: Using a traditional Python loop -------------

# Step 3: Record the start time for the loop-based operation
start_time_loop = time.time()

# Step 4: Initialize an empty NumPy array of zeros to store the results of the loop
result_loop = np.zeros(size)

# Step 5: Perform element-wise addition using a for-loop
# Iterate through each index and add the corresponding elements from both arrays
for i in range(size):
    result_loop[i] = array1[i] + array2[i]

# Step 6: Record the end time after the loop completes
end_time_loop = time.time()

# Step 7: Calculate the total time taken for the loop-based operation
time_loop = end_time_loop - start_time_loop

# ------------- Method 2: Using NumPy's vectorized operation -------------

# Step 8: Record the start time for the NumPy vectorized operation
start_time_vectorized = time.time()

# Step 9: Perform element-wise addition using NumPy's built-in vectorization
#This single line replaces the entire for-loop and is much faster
result_vectorized = array1 + array2

# Step 10: Record the end time after the vectorized operation completes
end_time_vectorized = time.time()

# Step 11: Calculate the total time taken for the vectorized operation
time_vectorized = end_time_vectorized - start_time_vectorized

# -------------- Output the results ---------------

# Step 12: Print the time taken by the loop method
print(f"Time taken using loop: {time_loop:.6f} seconds")

# Step 13: Print the time taken by the NumPy vectorized method
print(f"Time taken using NumPy vectorization: {time_vectorized:.6f} seconds")

# Step 14: Comparison NumPy's vectorized operation should be much faster than the loop!

Time taken using loop: 0.310446 seconds
Time taken using NumPy vectorization: 0.002602 seconds
